FROM golang:latest

# Set workdir inside the container
WORKDIR /app

# Copy go mod and sum files
COPY go.mod go.sum ./

RUN go mod download

# Copy the src from the current directory to the working directory inside the container
COPY . .

RUN go build -o main .

EXPOSE 8080

CMD ["./main"]
